<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ModulesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('modules')->insert([
        	[
	        	'id' => 'metadata',
	            'title' => 'Metadata',
	            'logo' => '/metadata.png',
	            'description' => 'Enumerator data, time and date, location, GPS, consent, enumerator notes',
	            'theme_id' => '0',
	            'minutes' => '4',
	            'core' => '1',
	            // 'file' => 'Rhomis_core_v1.6draftv5_Nov12.xlsx',

        	],
        	[
	        	'id' => 'household-demographics',
	            'title' => 'HOUSEHOLD DEMOGRAPHICS',
	            'logo' => '/household_demographics.png',
	            'description' => 'Name, sex, age, education, h/h population',
	            'theme_id' => '1',
	            'minutes' => '4',
	            'core' => '1',
	            'file' => 'Rhomis_core_v1.6draftv5_Nov12.xlsx',
        	],
        	[
	        	'id' => 'land-use',
	            'title' => 'LAND USE',
	            'logo' => '/land_use.png',
	            'description' => 'Tenure, cultivation, land area, slope, labour',
	            'theme_id' => '2',
	            'minutes' => '5',
	            'core' => '1',
	            'file' => 'Rhomis_core_v1.6draftv5_Nov12.xlsx',
        	],
        	[
	        	'id' => 'crop-production-and-use',
	            'title' => 'CROP PRODUCTION AND USE',
	            'logo' => '/crop_production_and_use.png',
	            'description' => 'Crop types, planting seasons, yield, use of land, post-harvest, sales, residues, crop products, planning',
	            'theme_id' => '2',
	            'minutes' => '10',
	            'core' => '1',
	            'file' => 'Rhomis_core_v1.6draftv5_Nov12.xlsx',
        	],
        	[
	        	'id' => 'agricultural-inputs-and-management',
	            'title' => 'AGRICULTURAL INPUTS AND MANAGEMENT',
	            'logo' => '/agricultural_inputs_and_management.png',
	            'description' => 'Fertilisers, pesticides, improved seed, storage, irrigation, agroforestry, tillage',
	            'theme_id' => '2',
	            'minutes' => '5',
	            'core' => '1',
	            'file' => 'Rhomis_core_v1.6draftv5_Nov12.xlsx',
        	],
        	[
	        	'id' => 'livestock',
	            'title' => 'LIVESTOCK',
	            'logo' => '/livestock.png',
	            'description' => 'Livestock types, numbers, grazing land, pens/stabling use of animals, buying, selling, slaughtering, eating, medicine, dairy/egg/honey/wool',
	            'theme_id' => '2',
	            'minutes' => '10',
	            'core' => '1',
	            'file' => 'Rhomis_core_v1.6draftv5_Nov12.xlsx',
        	],
        	[
	        	'id' => 'wildfoods',
	            'title' => 'WILDFOODS',
	            'logo' => '/wildfoods.png',
	            'description' => 'Gathering, types, time of year, processing, sales',
	            'theme_id' => '3',
	            'minutes' => '4',
	            'core' => '1',
	            'file' => 'Rhomis_core_v1.6draftv5_Nov12.xlsx',
        	],
        	[
	        	'id' => 'food-security-and-hunger',
	            'title' => 'FOOD SECURITY AND HUNGER',
	            'logo' => '/food_security_and_hunger.png',
	            'description' => 'Hunger months, HFIAS or FIES indicator',
	            'theme_id' => '3',
	            'minutes' => '4',
	            'core' => '1',
	            'file' => 'Rhomis_core_v1.6draftv5_Nov12.xlsx',
        	],
        	[
	        	'id' => 'household-dietary-diversity',
	            'title' => 'HOUSEHOLD DIETARY DIVERSITY',
	            'logo' => '/house_dietary_diversity.png',
	            'description' => 'HDDS score during lean and post-harvest seasons, and sourcing of foodstuffs',
	            'theme_id' => '3',
	            'minutes' => '5',
	            'core' => '1',
	            'file' => 'Rhomis_core_v1.6draftv5_Nov12.xlsx'
        	],
        	[
	        	'id' => 'off-farm-income',
	            'title' => 'OFF-FARM INCOME',
	            'logo' => '/off_farm_income.png',
	            'description' => 'Sources of income, time of year, planning, spending',
	            'theme_id' => '4',
	            'minutes' => '7',
	            'core' => '1',
	            'file' => 'Rhomis_core_v1.6draftv5_Nov12.xlsx'
        	],
        	[
	        	'id' => 'gendered-control-of-produce-and-incomes',
	            'title' => 'GENDERED CONTROL OF PRODUCE AND INCOMES',
	            'logo' => '/gender_control_of_produce_and_incomes.png',
	            'description' => 'Sources of income, time of year, planning, spending',
	            'theme_id' => '6',
	            'minutes' => '7',
	            'core' => '1',
	            'file' => 'Rhomis_core_v1.6draftv5_Nov12.xlsx'       	],
        	[
	        	'id' => 'credit-aid-and-debts',
	            'title' => 'CREDIT, AID, AND DEBTS',
	            'logo' => '/credit_aid_and_debts.png',
	            'description' => 'Government/NGO assistance, support from friends, type of aid, access to credit',
	            'theme_id' => '4',
	            'minutes' => '4',
	            'core' => '1',
	            'file' => 'Rhomis_core_v1.6draftv5_Nov12.xlsx',
        	],
        	[
	        	'id' => 'probability-of-poverty-indicator',
	            'title' => 'PROBABILITY OF POVERTY INDICATOR',
	            'logo' => '/probability_of_poverty_indicator.png',
	            'description' => 'Asset-based rapid poverty indicator',
	            'theme_id' => '4',
	            'minutes' => '4',
	            'core' => '1',
	            'file' => 'Rhomis_core_v1.6draftv5_Nov12.xlsx',
        	],
        	[
	        	'id' => 'agroforestry',
	            'title' => 'AGROFORESTRY',
	            'logo' => '/agroforestry.png',
	            'description' => 'Use of trees, quantity of trees used, species, management',
	            'theme_id' => '5',
	            'minutes' => '7',
	            'core' => '0',
	            'file' => 'Module-Agroforestry.xlsx',
        	],
        	[
	        	'id' => 'livestock-feeding',
	            'title' => 'LIVESTOCK FEEDING',
	            'logo' => '/livestock_feeding.png',
	            'description' => 'Type of feed, grazing, bought feeds',
	            'theme_id' => '2',
	            'minutes' => '3',
	            'core' => '0',
	            'file' => 'Module-Livestock_feeding.xlsx',

        	],
        	[
	        	'id' => 'bushmeat',
	            'title' => 'BUSHMEAT',
	            'logo' => '/bushmeat.png',
	            'description' => 'Hunting and trapping, species, and frequency',
	            'theme_id' => '3',
	            'minutes' => '7',
	            'core' => '0',
	            'file' => 'Module-Bushmeat.xlsx',
        	],
        	[
	        	'id' => 'cattle-detailed',
	            'title' => 'CATTLE DETAILED',
	            'logo' => '/cattle_detailed.png',
	            'description' => 'Herd structure, age, sex, breeding, milking, diseases and health treatments',
	            'theme_id' => '2',
	            'minutes' => '15',
	            'core' => '0',
	            'file' => 'Module-Cattle_detailed.xlsx',
        	],
        	[
	        	'id' => 'changes-on-farm',
	            'title' => 'CHANGES ON FARM',
	            'logo' => '/changes_on_farm.png',
	            'description' => 'Changes over past few years: land, crop types and yields, inputs, livestock, sales, incomes, off farm work, reasons for changes',
	            'theme_id' => '1',
	            'minutes' => '7',
	            'core' => '0',
	            'file' => 'Module-Changes on Farm.xlsx',
        	],
        	[
	        	'id' => 'coping-strategies',
	            'title' => 'COPING STRATEGIES',
	            'logo' => '/coping_strategies.png',
	            'description' => 'Coping strategy index (CSI), changes of food access over the year',
	            'theme_id' => '4',
	            'minutes' => '5',
	            'core' => '0',
	            'file' => 'Module-Coping_strategy.xlsx',
        	],
        	[
	        	'id' => 'disability',
	            'title' => 'DISABILITY',
	            'logo' => '/disability.png',
	            'description' => 'Quantification of disabled individuals in household (Washington Group questions)',
	            'theme_id' => '4',
	            'minutes' => '4',
	            'core' => '0',
	            'file' => 'Module-Disability.xlsx',
        	],
        	[
	        	'id' => 'fies',
	            'title' => 'FIES',
	            'logo' => '/food_insecurity_experience_scale.png',
	            'description' => 'Food Insecurity Experience Scale (FIES)',
	            'theme_id' => '3',
	            'minutes' => '4',
	            'core' => '0',
	            'file' => 'Module-FIES.xlsx',
        	],
        	[
	        	'id' => 'hfias',
	            'title' => 'HFIAS',
	            'logo' => '/household_food_insecurity_access_scale.png',
	            'description' => 'Household Food Insecurity of Access Scale (HFIAS)',
	            'theme_id' => '3',
	            'minutes' => '4',
	            'core' => '0',
	            'file' => 'Module-HFIAS.xlsx',
        	],
        	[
	        	'id' => 'mdd-w',
	            'title' => 'MDD-W',
	            'logo' => '/minimun_dietary_diversity_for_women.png',
	            'description' => 'Minimum Dietary Diversity for Women (open recall or closed categories)',
	            'theme_id' => '3',
	            'minutes' => '4',
	            'core' => '0',
	            'file' => 'Module-MDDW.xlsx',
        	],
        	[
	        	'id' => 'financial-situation',
	            'title' => 'FINANCIAL SITUATION',
	            'logo' => '/financial_situation.png',
	            'description' => 'Self-identified purchasing power',
	            'theme_id' => '4',
	            'minutes' => '2',
	            'core' => '0',
	            'file' => 'Module-Financial_situation.xlsx',
        	],
        	[
	        	'id' => 'food-environments',
	            'title' => 'FOOD ENVIRONMENTS',
	            'logo' => '/food_environments.png',
	            'description' => 'Market access, packaged food',
	            'theme_id' => '3',
	            'minutes' => '4',
	            'core' => '0',
	            'file' => 'Module-Food_environments.xlsx',
        	],
        	[
	        	'id' => 'innovation',
	            'title' => 'INNOVATION',
	            'logo' => '/innovation.png',
	            'description' => 'Farm plans, adoption of new technologies, aspirations, life satisfaction',
	            'theme_id' => '1',
	            'minutes' => '4',
	            'core' => '0',
	            'file' => 'Module-Innovation.xlsx',
        	],
        	[
	        	'id' => 'expenditures',
	            'title' => 'EXPENDITURES',
	            'logo' => '/expenditures.png',
	            'description' => 'Sources of income, spending of income - family costs, farm costs, giving to others',
	            'theme_id' => '4',
	            'minutes' => '4',
	            'core' => '0',
	            'file' => 'Module-Expenditures.xlsx',
        	],
        	[
	        	'id' => 'membership-of-groups',
	            'title' => 'MEMBERSHIP OF GROUPS',
	            'logo' => '/membership_of_groups.png',
	            'description' => 'Farmer groups, credit unions, cooperatives, leadership roles',
	            'theme_id' => '1',
	            'minutes' => '4',
	            'core' => '0',
	            'file' => 'Module-Membership_groups.xlsx',
        	],
        	[
	        	'id' => 'nrm-perception',
	            'title' => 'NRM PERCEPTION',
	            'logo' => '/nrm_perception.png',
	            'description' => 'Change of experience relating to soil, water, weather, fauna, trees',
	            'theme_id' => '2',
	            'minutes' => '4',
	            'core' => '0',
	            'file' => 'Module-NRM_perception.xlsx',
        	],
        	[
	        	'id' => 'relative-vulnerability',
	            'title' => 'RELATIVE VULNERABILITY',
	            'logo' => '/relative_vulnerability.png',
	            'description' => 'Vulnerability to shocks compared to neighbours',
	            'theme_id' => '4',
	            'minutes' => '5',
	            'core' => '0',
	            'file' => 'Module-Relative_Vulnerability.xlsx',
        	],
        	[
	        	'id' => 'slash-and-burn',
	            'title' => 'SLASH AND BURN',
	            'logo' => '/slash_and_burn.png',
	            'description' => 'Clearing land, change of use, fallow practices',
	            'theme_id' => '5',
	            'minutes' => '4',
	            'core' => '0',
	            'file' => 'Module-SlashnBurn.xlsx',
        	],
        	[
	        	'id' => 'uptake-of-interventions',
	            'title' => 'UPTAKE OF INTERVENTIONS',
	            'logo' => '/uptake_of_interventions.png',
	            'description' => 'New practices trialled and evaluated',
	            'theme_id' => '1',
	            'minutes' => '10',
	            'core' => '0',
	            'file' => 'Module-Uptake_of_interventions.xlsx',
        	],
        	[
	        	'id' => 'value-orientations',
	            'title' => 'VALUE ORIENTATIONS',
	            'logo' => '/value_orientations.png',
	            'description' => 'Value orientations: selfbenefit, community-benefit, innovative, conservative',
	            'theme_id' => '1',
	            'minutes' => '4',
	            'core' => '0',
	            'file' => 'Module-Value_orientations.xlsx',
        	],
        	[
	        	'id' => 'wash',
	            'title' => 'WASH',
	            'logo' => '/wash.png',
	            'description' => 'Water source, access, storage, hand cleaning, sanitation',
	            'theme_id' => '4',
	            'minutes' => '4',
	            'core' => '0',
	            'file' => 'Module-WASH.xlsx',
        	],
        	[
	        	'id' => 'forest-products',
	            'title' => 'FOREST PRODUCTS',
	            'logo' => '/forest_products.png',
	            'description' => 'Harvesting, processing, and use of Non-Timber Forest Products and Woody Forest Products',
	            'theme_id' => '5',
	            'minutes' => '7',
	            'core' => '0',
	            'file' => 'Module-Forest_products.xlsx',
        	],
        	[
	        	'id' => 'voice-choice-control',
	            'title' => 'VOICE CHOICE CONTROL',
	            'logo' => '/voice_choice_control.png',
	            'description' => 'Gendered experiences of power and communication outside the home',
	            'theme_id' => '6',
	            'minutes' => '5',
	            'core' => '0',
	            'file' => 'Module-Voice_choice_control.xlsx',
        	],
        	[
	        	'id' => 'forest-governance',
	            'title' => 'FOREST GOVERNANCE',
	            'logo' => '/forest_governance.png',
	            'description' => 'Community forest governance structures',
	            'theme_id' => '5',
	            'minutes' => '8',
	            'core' => '0',
	            'file' => 'Module-Forest_governance.xlsx',
        	],
        	[
	        	'id' => 'plot-level-land-use-and-boundaries',
	            'title' => 'PLOT-LEVEL LAND USE AND BOUNDARIES',
	            'logo' => '/plot_level_land_use_and_boundaries.png',
	            'description' => 'GPS boundaries of plots, plot level land use and history',
	            'theme_id' => '2',
	            'minutes' => '60',
	            'core' => '0',
	            'file' => 'Module-Plot_level_land_use_boundaries.xlsx',
        	],
        	[
	        	'id' => 'gender-attitudes',
	            'title' => 'GENDER ATTITUDES',
	            'logo' => '/gender_attitudes.png',
	            'description' => 'Mobility, decision making, violence, care for others',
	            'theme_id' => '6',
	            'minutes' => '8',
	            'core' => '0',
	            'file' => 'Module-Gender_attitudes.xlsx',
        	],
        	[
	        	'id' => 'gendered-labour-and-time-allocation',
	            'title' => 'GENDERED LABOUR AND TIME ALLOCATION',
	            'logo' => '/gendered_labour_and_time_allocation.png',
	            'description' => '24 hour time allocation, work allocation in farm and home',
	            'theme_id' => '6',
	            'minutes' => '8',
	            'core' => '0',
	            'file' => 'Module-Gender_labour_time.xlsx',
        	],
        	[
	        	'id' => 'crop-pests',
	            'title' => 'CROP PESTS',
	            'logo' => '/crop_pests.png',
	            'description' => 'Pictoral estimation of crop pests occurance and damage (focus on fall army worm)',
	            'theme_id' => '2',
	            'minutes' => '10',
	            'core' => '0',
	            'file' => 'Module-Crop_pests.xlsx',
        	],
        	[
	        	'id' => 'seed-varieties',
	            'title' => 'SEED VARIETIES',
	            'logo' => '/seed_varieties.png',
	            'description' => 'Uptake and use of improved crop seed varieties',
	            'theme_id' => '2',
	            'minutes' => '5',
	            'core' => '0',
	            'file' => 'Module-Seed_varieties.xlsx',
        	],
        ]);
    }
}
